# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cheerp - Documentation
description: >- # this means to ignore newlines until "baseurl:"
  Main documentation and tutorials for Cheerp | the C++ compiler for the Web.
baseurl: "/cheerpj-meta" # the subpath of your site, e.g. /blog
logo: "/assets/cheerj_logo.png"   # Change to relevant file
tagline:
  line1: "CheerpJ - the Java solution for the Web"
  line2: "Documentation & Tutorials"

social_links:
  twitter: leaningtech
  github:  leaningtech
  medium:  leaningtech
  linkedin: leaning-technologies-Ltd

download: "https://leaningtech.com/cheerpj-download/"

# Build settings
markdown: kramdown
remote_theme: leaningtech/leaningtech-docs

plugins:
 - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: "https://opengraph.githubassets.com/0695f40a0d2d9ee5d8871e5f80042de3b061f7496b092d086712709c9d0f1a6e/leaningtech/cheerpj-meta"

repository: https://github.com/leaningtech/cheerpj-meta
website: https://leaningtech.com/cheerpj/
issues: https://github.com/leaningtech/cheerpj-meta/issues
chat: https://gitter.im/leaningtech/cheerpj
blog: https://medium.com/leaningtech
has_about: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
